-- Backward-compatible public outlet metadata (all nullable).

ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "displayName" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "alternatePhone" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "addressLine2" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "landmark" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "area" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "formattedAddress" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "openingTime" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "closingTime" TEXT;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "estimatedDeliveryMinutes" INTEGER;
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "googleMapsUrl" TEXT;

ALTER TABLE "OutletProfile" ADD COLUMN IF NOT EXISTS "supportWhatsapp" TEXT;
