export enum ProductTag {
  FRESH = 'FRESH',
  ORGANIC = 'ORGANIC',
  NO_SUGAR = 'NO_SUGAR',
  COLD_PRESSED = 'COLD_PRESSED',
  NATURAL = 'NATURAL',
  FARM_FRESH = 'FARM_FRESH',
  PRESERVATIVE_FREE = 'PRESERVATIVE_FREE',
  VEGAN = 'VEGAN',
}
