import { CSSProperties } from "react";

export const styles: { [key: string]: React.CSSProperties } = {
  container: { padding: "40px", backgroundColor: "#F8FAFC", minHeight: "100vh", fontFamily: "'Inter', sans-serif" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "32px" },
  title: { fontSize: "28px", fontWeight: "800", color: "#0F172A", margin: 0 },
  subtitle: { color: "#64748B", fontSize: "14px", marginTop: "4px" },
  createBtn: { backgroundColor: "#0F172A", color: "white", padding: "12px 24px", borderRadius: "12px", border: "none", fontWeight: "600", cursor: "pointer" },
  tableWrapper: { backgroundColor: "white", borderRadius: "16px", border: "1px solid #E2E8F0", overflow: "hidden", boxShadow: "0 10px 15px -3px rgba(0,0,0,0.05)" },
  table: { width: "100%", borderCollapse: "collapse" },
  th: { backgroundColor: "#F8FAFC", padding: "18px 24px", fontSize: "12px", fontWeight: "700", color: "#64748B", textAlign: "left", borderBottom: "1px solid #E2E8F0" },
  tr: { borderBottom: "1px solid #F1F5F9", transition: "all 0.3s ease" },
  td: { padding: "20px 24px", verticalAlign: "middle" },
  nameGroup: { display: "flex", flexDirection: "column" },
  nameText: { fontWeight: "600", color: "#1E293B", fontSize: "15px" },
  branchBadge: { fontSize: "12px", color: "#94A3B8" },
  statusBadge: { display: "flex", alignItems: "center", gap: "6px", padding: "6px 14px", borderRadius: "99px", fontSize: "12px", fontWeight: "700" },
  dot: { width: "6px", height: "6px", borderRadius: "50%" },
  select: { padding: "8px 12px", borderRadius: "10px", border: "1px solid #CBD5E1", fontSize: "13px", cursor: "pointer", outline: 'none' },
  toggleSwitch: { width: "44px", height: "24px", borderRadius: "12px", position: "relative", border: "none", cursor: "pointer" },
  toggleThumb: { width: "20px", height: "20px", backgroundColor: "white", borderRadius: "50%", position: "absolute", top: "2px", transition: "0.2s" },
  iconBtn: { background: "none", border: "none", cursor: "pointer", padding: "8px", borderRadius: "8px" },
  modalOverlay: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(15, 23, 42, 0.4)", backdropFilter: "blur(6px)", zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center" },
  editModal: { backgroundColor: "white", width: "550px", borderRadius: "24px", padding: "40px", boxShadow: "0 25px 50px -12px rgba(0,0,0,0.25)" },
  modal: { backgroundColor: "white", padding: "40px", borderRadius: "24px", maxWidth: "420px", width: "90%", textAlign: "center", boxShadow: "0 25px 50px -12px rgba(0,0,0,0.25)" },
  modalTitle: { margin: "0 0 12px 0", fontSize: "20px", fontWeight: "700" },
  modalActions: { display: "flex", gap: "12px" },
  modalCancel: { flex: 1, padding: "14px", borderRadius: "12px", border: "1px solid #E2E8F0", cursor: "pointer", fontWeight: '600' },
  modalConfirm: { flex: 1, padding: "14px", borderRadius: "12px", border: "none", color: "white", fontWeight: "700", cursor: "pointer" },
  drawerHeader: { display: "flex", justifyContent: "space-between", marginBottom: "32px" },
  drawerTitle: { fontSize: "24px", fontWeight: "800", color: "#0F172A" },
  closeBtn: { background: "none", border: "none", fontSize: "22px", cursor: "pointer", color: "#94A3B8" },
  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" },
  inputGroup: { display: "flex", flexDirection: "column", gap: "8px" },
  label: { fontSize: "14px", fontWeight: "600" },
  input: { padding: "12px", borderRadius: "10px", border: "1.5px solid #E2E8F0", outline: 'none' },
  saveBtn: { width: "100%", padding: "14px", backgroundColor: "#0F172A", color: "white", borderRadius: "12px", fontWeight: "700", marginTop: "32px", cursor: "pointer" },
  loader: { height: "100vh", display: "flex", alignItems: "center", justifyContent: "center" },
  error: { color: "#EF4444", padding: "40px", textAlign: "center" },
  errorBanner: { backgroundColor: "#FEF2F2", color: "#B91C1C", padding: "12px", borderRadius: "10px", fontSize: "13px", fontWeight: "600", marginBottom: "20px" },
  idBadge: { backgroundColor: "#F1F5F9", color: "#64748B", padding: "4px 8px", borderRadius: "6px", fontSize: "12px", fontWeight: "700" },
  checkboxContainer: { display: "flex", alignItems: "center", gap: "10px", cursor: "pointer" },
  checkboxTitle: { fontSize: "14px", fontWeight: "600", color: "#1E293B" }
};